language: elixir
elixir:
- 1.4.1
otp_release:
- 19.3
sudo: false
script:
  - mix test
  - mix escript.build
deploy:
  provider: releases
  api_key:
    secure: ebGuImRgtVobmiD/kbdEE2YL14Mm5rdPMxATxXijmBv9vwgAInpDNJVAbkYjwPIdi5atKFRtbOsrG9Rnnob4/V0wvk6puFPHLAPYV8uzZUhUkpQpj75q8Lwbf5Ipb9VJ4tsYH8KJ7y8FBfm/3brlJXJ4twlapX7yVRsxtDwRdMzyFIfH9vhyENkaA5YxvT45YPNZhMvIgjuQNahk4KQhTLlKSjLXgsBgifjPon95ptH3i4Mf97JcKbA4RRvpMI9I5jqDiXsqjNoL3ZVtheZv+tIp+pnQPPG8SSssfcKBIMc4DsgasTfEXLuxYoyJHISj9kH7lhV7iAEq56pN4WNwUHmPCU6HlpmMKvDHF4RC94STkF+fUQylNwxRXmgxW5bjFiY0/R4mvAkIkIkbvOL468sHaCyfeNImKhHUMllflLqJWiKIuKJvi1mwGo2Z/sOq4X2LwS0wF+csHFeSwrKm5i8l4crfE1lugvp4KC8L2XSvtxEtXSLGq9ZCD5uIap7PI842QtCiBRDfWlJNcdTVO+sYgon22f87K6HppeXGZX5w5mOGjJGK37RHYtdfROQENur1oDyEQ+V8DGhH/NVO1xpDLAksD+Q4XkJtPVe9qEsxoOWLUxxET8S6AJO2R3dVrewdzxOwYOpbtAQfrYcYnfGNS/IYhsndlfWW2+sPcSo=
  file: release/exorch
  on:
    repo: leg100/exorch
